<?php

namespace Database\Seeders;

use App\Models\Hero;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HeroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Hero::insert([
            ['name' => 'Wiro', 'image' => 'Wiro.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Max', 'image' => 'Max.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Cresht', 'image' => 'Cresht.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Grakk', 'image' => 'Grakk.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Taara', 'image' => 'Taara.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Toro', 'image' => 'Toro.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Gildur', 'image' => 'Gildur.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Omega', 'image' => 'Omega.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Mina', 'image' => 'Mina.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Thane', 'image' => 'Thane.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn'],
            ['name' => 'Chaugnar', 'image' => 'Chaugnar.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn & Trợ thủ'],
            ['name' => 'Xeniel', 'image' => 'Xeniel.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn & Trợ thủ'],
            ['name' => "Y'bneth", 'image' => "Y'bneth.jpg", 'position' => 'Đường ...', 'role' => 'Đỡ đòn & Trợ thủ'],
            ['name' => 'Baldum', 'image' => 'Baldum.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn & Trợ thủ'],
            ['name' => 'Arum', 'image' => 'Arum.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn & Trợ thủ'],
            ['name' => 'Lumburr', 'image' => 'Lumburr.jpg', 'position' => 'Đường ...', 'role' => 'Đỡ đòn & Trợ thủ'],
            ['name' => 'Edras', 'image' => 'Edras.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Biron', 'image' => 'Biron.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Charlotte', 'image' => 'Charlotte.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Tachi', 'image' => 'Tachi.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Qi', 'image' => 'Qi.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Bijan', 'image' => 'Bijan.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Yan', 'image' => 'Yan.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Dextra', 'image' => 'Dextra.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Allain', 'image' => 'Allain.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Ata', 'image' => 'Ata.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Volkath', 'image' => 'Volkath.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Yena', 'image' => 'Yena.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Errol', 'image' => 'Errol.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Veres', 'image' => 'Veres.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Florentino', 'image' => 'Florentino.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Richter', 'image' => 'Richter.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Amily', 'image' => 'Amily.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Roxie', 'image' => 'Roxie.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Rourke', 'image' => 'Rourke.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Omen', 'image' => 'Omen.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => "Kil'Groth", 'image' => "Kil'Groth.jpg", 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Wonder Woman', 'image' => 'Wonder Woman.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Superman', 'image' => 'Superman.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Astrid', 'image' => 'Astrid.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Ryoma', 'image' => 'Ryoma.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Arduin', 'image' => 'Arduin.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Zuka', 'image' => 'Zuka.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Skud', 'image' => 'Skud.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Arthur', 'image' => 'Arthur.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Maloch', 'image' => 'Maloch.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Ormarr', 'image' => 'Ormarr.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Triệu Vân', 'image' => 'Triệu Vân.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Lữ Bố', 'image' => 'Lữ Bố.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ'],
            ['name' => 'Bolt Baron', 'image' => 'Bolt Baron.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ & Pháp sư'],
            ['name' => 'Zephys', 'image' => 'Zephys.jpg', 'position' => 'Đường ...', 'role' => 'Đấu sĩ & Sát thủ'],
            ['name' => 'Heino', 'image' => 'Heino.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Goverra', 'image' => 'Goverra.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => "D' Arcy", 'image' => "D' Arcy.jpg", 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Erin', 'image' => 'Erin.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Bonnie', 'image' => 'Bonnie.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Iggy', 'image' => 'Iggy.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Yue', 'image' => 'Yue.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Lorion', 'image' => 'Lorion.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Zata', 'image' => 'Zata.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Dirak', 'image' => 'Dirak.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Ishar', 'image' => 'Ishar.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Krixi', 'image' => 'Krixi.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Kahlii', 'image' => 'Kahlii.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Điêu Thuyền', 'image' => 'Điêu Thuyền.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Mganga', 'image' => 'Mganga.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => "Azzen'Ka", 'image' => "Azzen'Ka.jpg", 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Aleister', 'image' => 'Aleister.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'The Flash', 'image' => 'The Flash.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Tulen', 'image' => 'Tulen.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Liliana', 'image' => 'Liliana.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Preyta', 'image' => 'Preyta.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Lauriel', 'image' => 'Lauriel.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Ilumia', 'image' => 'Ilumia.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Marja', 'image' => 'Marja.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Veera', 'image' => 'Veera.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Natalya', 'image' => 'Natalya.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Jinna', 'image' => 'Jinna.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Ignis', 'image' => 'Ignis.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư'],
            ['name' => 'Raz', 'image' => 'Raz.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư & Sát thủ'],
            ['name' => 'Zill', 'image' => 'Zill.jpg', 'position' => 'Đường ...', 'role' => 'Pháp sư & Sát thủ'],
            ['name' => 'Bright', 'image' => 'Bright.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Aoi', 'image' => 'Aoi.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Sinestrea', 'image' => 'Sinestrea.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Paine', 'image' => 'Paine.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Enzo', 'image' => 'Enzo.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Quillen', 'image' => 'Quillen.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Keera', 'image' => 'Keera.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Murad', 'image' => 'Murad.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Airi', 'image' => 'Airi.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Nakroth', 'image' => 'Nakroth.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Butterfly', 'image' => 'Butterfly.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Ngộ Không', 'image' => 'Ngộ Không.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Kriknak', 'image' => 'Kriknak.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Kaine', 'image' => 'Kaine.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ'],
            ['name' => 'Billow', 'image' => 'Billow.jpg', 'position' => 'Đường ...', 'role' => 'Sát thủ & Đấu sĩ'],
            ['name' => 'Ming', 'image' => 'Ming.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Helen', 'image' => 'Helen.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Aya', 'image' => 'Aya.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'TeeMee', 'image' => 'TeeMee.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Dolia', 'image' => 'Dolia.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Alice', 'image' => 'Alice.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Rouie', 'image' => 'Rouie.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Krizzix', 'image' => 'Krizzix.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Zip', 'image' => 'Zip.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Annette', 'image' => 'Annette.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Sephera', 'image' => 'Sephera.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ'],
            ['name' => 'Dyadia', 'image' => 'Dyadia.jpg', 'position' => 'Đường ...', 'role' => 'Trợ thủ & Pháp sư'],
            ['name' => 'Stuart', 'image' => 'Stuart.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Teeri', 'image' => 'Teeri.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Thorne', 'image' => 'Thorne.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Laville', 'image' => 'Laville.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Celica', 'image' => 'Celica.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Hayate', 'image' => 'Hayate.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Capheny', 'image' => 'Capheny.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Wisp', 'image' => 'Wisp.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Moren', 'image' => 'Moren.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Lindis', 'image' => 'Lindis.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => "Tel'Annas", 'image' => "Tel'Annas.jpg", 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Slimz', 'image' => 'Slimz.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Fennik', 'image' => 'Fennik.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Yorn', 'image' => 'Yorn.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Violet', 'image' => 'Violet.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Valhein', 'image' => 'Valhein.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => 'Elsu', 'image' => 'Elsu.jpg', 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
            ['name' => "Eland'orr", 'image' => "Eland'orr.jpg", 'position' => 'Đường ...', 'role' => 'Xạ thủ'],
        ]);
    }
}
